resolver: snapshot.yaml

packages:
- .

docker:
  enable: false
  repo: fpco/stack-build:lts-11.22

nix:
  # --nix on the command-line to enable.
  packages:
    - zlib
    - unzip
flags:
  stack:
    hide-dependency-versions: true
    supported-build: true

ghc-options:
   "$locals": -fhide-source-paths

extra-deps:

- github: fpco/casa
  commit: a0cd05c1a9ce33acbb1bdfb9324370f884916e88
  sha256: e21e5fa2b9fa03f37761d5b95559a09af578a9b10e9cad0baca4ccdb5cde1b78
  size: 10520
  subdirs:
     - casa-client
     - casa-types

- github: commercialhaskell/pantry
  commit: a67d0818de52de239d9e051a25cca6d29785e06d
  size: 95018
  sha256: 299dabb14beb81c39457be69eb80be3038868850dd0c28b02ebf98566757bbc8
